// autogenerated by sql-generate v0.3.0 on Wed May 14 2014 23:41:38 GMT-0700 (PDT)

module.exports = function(sql) {
	var exports = {};


	/**
	 * SQL definition for jello.event
	 */
	exports.event = sql.define({
		name: 'event',
		columns: [
			{ name: 'id' },
			{ name: 'event_definition_id' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.event_definition
	 */
	exports.event_definition = sql.define({
		name: 'event_definition',
		columns: [
			{ name: 'id' },
			{ name: 'tenant_id' },
			{ name: 'name' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.event_property_map
	 */
	exports.event_property_map = sql.define({
		name: 'event_property_map',
		columns: [
			{ name: 'event_id' },
			{ name: 'property_id' }
		]
	});


	/**
	 * SQL definition for jello.property
	 */
	exports.property = sql.define({
		name: 'property',
		columns: [
			{ name: 'id' },
			{ name: 'property_definition_id' },
			{ name: 'property_type_id' },
			{ name: 'value' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.property_definition
	 */
	exports.property_definition = sql.define({
		name: 'property_definition',
		columns: [
			{ name: 'id' },
			{ name: 'name' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.property_type
	 */
	exports.property_type = sql.define({
		name: 'property_type',
		columns: [
			{ name: 'id' },
			{ name: 'name' }
		]
	});


	/**
	 * SQL definition for jello.tenant
	 */
	exports.tenant = sql.define({
		name: 'tenant',
		columns: [
			{ name: 'id' },
			{ name: 'name' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.user
	 */
	exports.user = sql.define({
		name: 'user',
		columns: [
			{ name: 'id' },
			{ name: 'email' },
			{ name: 'password' },
			{ name: 'first_name' },
			{ name: 'last_name' },
			{ name: 'created' }
		]
	});


	/**
	 * SQL definition for jello.user_tenant_map
	 */
	exports.user_tenant_map = sql.define({
		name: 'user_tenant_map',
		columns: [
			{ name: 'user_id' },
			{ name: 'tenant_id' }
		]
	});


	return exports;
};
